name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  mix:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        # TODO or latest-alpine ???
        image: clickhouse/clickhouse-server:22.6.3-alpine
        ports:
          - 9000:9000
        env:
          options: >-
            --health-cmd nc -zw3 localhost 9000
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - uses: actions/checkout@v3

      # TODO matrix
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.13.4"
          otp-version: "25.0.2"

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatted
        run: mix format --check-formatted

      - name: Compile (warnings as errors)
        run: MIX_ENV=test mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
